name: rickandmorty
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.3
  flutter_mobx: ^2.2.1+1
  intl: ^0.19.0
  get_storage: ^2.1.1
  http: ^1.2.1
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.16
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/svg/
